Repository spess14/trailblazer-colony-14, pull requests merged in 2025-03, with the labels that each got.

#30 rimblazer lobby art by key2105
  Resources/IgnoredPrototypes/ignoredPrototypes.yml
  Resources/Prototypes/_tc14/lobbyscreens.yml
  Resources/Textures/LobbyScreens/attributions.yml
  Resources/Textures/LobbyScreens/rimblazer.webp
  Resources/Textures/LobbyScreens/rimblazer.webp.yml
Labels: Changes: No C#

#31 Adds a new images to replace old smeltery.
  Resources/Textures/Structures/Machines/smeltery.rsi/icon.png
  Resources/Textures/Structures/Machines/smeltery.rsi/meta.json
  Resources/Textures/Structures/Machines/smeltery.rsi/working.png
Labels: Changes: No C#, Changes: Sprites

#32 Workbenchart
  Resources/Textures/Structures/Machines/workbench.rsi/workbench.png
Labels: Changes: No C#, Changes: Sprites

#34 Adds early tech sprites!
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/bpblank.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/fullbp.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/meta.json
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/techpaperlargelstack.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/techpapersingle.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/techpapersmallstack.png
  Resources/Textures/Structures/Machines/earlyresearchbench.rsi/earlyresearchbench.png
  Resources/Textures/Structures/Machines/earlyresearchbench.rsi/meta.json
Labels: Changes: No C#, Changes: Sprites

#38 Add animations to teh workbench
  Resources/Textures/Structures/Machines/earlyresearchbench.rsi/earlyresearchbench.png
  Resources/Textures/Structures/Machines/earlyresearchbench.rsi/meta.json
Labels: Changes: No C#, Changes: Sprites

#43 Coal PACMAN
  Resources/Prototypes/Recipes/Lathes/Packs/engineering.yml
  Resources/Prototypes/_tc14/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/_tc14/Entities/Structures/Power/Generation/portable_generator.yml
  Resources/Prototypes/_tc14/Recipes/Lathes/Packs/workbench.yml
  Resources/Prototypes/_tc14/Recipes/Lathes/electronics.yml
  Resources/Textures/Structures/Power/Generation/portable_generator.rsi/meta.json
  Resources/Textures/Structures/Power/Generation/portable_generator.rsi/portgen4.png
  Resources/Textures/Structures/Power/Generation/portable_generator.rsi/portgen4on.png
Labels: Changes: No C#, Changes: Sprites

#48 recipe for stone tools
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Prototypes/_tc14/Entities/Objects/Tools/rocks.yml
  Resources/Prototypes/_tc14/Entities/Objects/Tools/stone.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/Graphs/tools.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/tools.yml
  Resources/Prototypes/_tc14/tags.yml
Labels: Changes: No C#

#49 reduce worldgen spawnrate
  Resources/Prototypes/_tc14/Procedural/biome_templates.yml
Labels: Changes: No C#

#56 adds stuff
  Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml
  Resources/Prototypes/_tc14/Entities/Objects/Decoration/flora.yml
  Resources/Prototypes/_tc14/Entities/Objects/Weapons/Guns/Projectiles/arrows.yml
  Resources/Prototypes/_tc14/Recipes/Construction/Graphs/weapons/improvised_arrow.yml
  Resources/Prototypes/_tc14/Recipes/Construction/weapons.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/Graphs/tools.yml
Labels: Changes: No C#, Changes: Map
