Repository spess14/trailblazer-colony-14, pull requests merged in 2025-04, with the labels that each got.

#58 Digging soil + soil craft
  Content.Server/Tiles/SoilDiggingSystem.cs
  Content.Shared/Maps/ContentTileDefinition.cs
  Content.Shared/Tiles/SoilDigEvent.cs
  Content.Shared/Tiles/SoilDiggingSystem.cs
  Resources/Prototypes/Entities/Structures/soil.yml
  Resources/Prototypes/Tiles/planet.yml
  Resources/Prototypes/_tc14/Entities/Objects/Materials/soils.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/Graphs/Structures/botany.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/structures.yml
  Resources/Prototypes/_tc14/Stacks/Materials/soils.yml
  Resources/Textures/_tc14/Objects/Materials/materials.rsi/dirt.png
  Resources/Textures/_tc14/Objects/Materials/materials.rsi/meta.json
Labels: Changes: Sprites

#59 remove cloth from bushes
  Resources/Prototypes/_tc14/Entities/Objects/Decoration/flora.yml
Labels: Changes: No C#

#64 Planetary events - meteors
  Resources/Locale/en-US/_tc14/events/events.ftl
  Resources/Prototypes/_tc14/Gamerules/meteorswarms.yml
  Resources/Prototypes/_tc14/Gamerules/roundstart.yml
  Resources/Prototypes/_tc14/game_presets.yml
Labels: Changes: No C#

#66 Revert "Revert "Planetary events - meteors""
  Resources/Locale/en-US/_tc14/events/events.ftl
  Resources/Prototypes/_tc14/Gamerules/meteorswarms.yml
  Resources/Prototypes/_tc14/Gamerules/roundstart.yml
  Resources/Prototypes/_tc14/game_presets.yml
Labels: Changes: No C#

#68 Revert "Revert "Revert "Planetary events - meteors"""
  Resources/Locale/en-US/_tc14/events/events.ftl
  Resources/Prototypes/_tc14/Gamerules/meteorswarms.yml
  Resources/Prototypes/_tc14/Gamerules/roundstart.yml
  Resources/Prototypes/_tc14/game_presets.yml
Labels: Changes: No C#

#67 Planetary event
  Content.Server/GameTicking/Rules/Components/PlanetBecomesStationRuleComponent.cs
  Content.Server/GameTicking/Rules/PlanetBecomesStationRuleSystem.cs
  Resources/Prototypes/_tc14/Gamerules/roundstart.yml
  Resources/Prototypes/_tc14/game_presets.yml
Labels: S: Merge Conflict

#71 Reordered the rules a bit. Also rephrased 1-7.
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-0.xml
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-1.xml
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-2.xml
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-3.xml
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-4.xml
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-5.xml
  Resources/ServerInfo/_tc14/ServerRules/RoleplayRules/1-7.xml
  Resources/ServerInfo/_tc14/ServerRules/TCRules.xml
Labels: Changes: No C#, S: Needs Review

#47 Early-game research system
  Content.Client/Blueprint/UI/BluebenchBoundUserInterface.cs
  Content.Client/Blueprint/UI/BluebenchMaterialRequirement.xaml
  Content.Client/Blueprint/UI/BluebenchMaterialRequirement.xaml.cs
  Content.Client/Blueprint/UI/BluebenchMenu.xaml
  Content.Client/Blueprint/UI/BluebenchMenu.xaml.cs
  Content.Client/Blueprint/UI/BluebenchResearchEntry.xaml
  Content.Client/Blueprint/UI/BluebenchResearchEntry.xaml.cs
  Content.Shared/Blueprint/BluebenchBoundUserInterfaceState.cs
  Content.Shared/Blueprint/BluebenchComponent.cs
  Content.Shared/Blueprint/BluebenchResearchPrototype.cs
  Content.Shared/Blueprint/BluebenchSystem.cs
  Content.Shared/Blueprint/Shared.cs
  Content.Shared/Research/Components/BlueprintComponent.cs
  Content.Shared/Research/Systems/BlueprintSystem.cs
  Resources/Locale/en-US/_tc14/bluebench.ftl
  Resources/Prototypes/Entities/Objects/Tools/blueprint.yml
  Resources/Prototypes/_tc14/Entities/Objects/Materials/Sheets/other.yml
  Resources/Prototypes/_tc14/Entities/Structures/Machines/workbench.yml
  Resources/Prototypes/_tc14/research_projects.yml
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/bluepaper.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/bluepaper_2.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/bluepaper_3.png
  Resources/Textures/Objects/Materials/researchearlytechpaper.rsi/meta.json
Labels: Changes: Sprites, Changes: UI, S: Needs Review
