Repository spess14/trailblazer-colony-14, pull requests merged in 2025-05, with the labels that each got.

#73 2 researches
  Resources/Prototypes/_tc14/research_projects.yml
Labels: Changes: No C#

#75 Bluebench stuff part 2
  Content.Client/Blueprint/UI/BluebenchBoundUserInterface.cs
  Content.Client/Blueprint/UI/BluebenchMenu.xaml
  Content.Client/Blueprint/UI/BluebenchMenu.xaml.cs
  Content.Client/Blueprint/UI/BluebenchResearchEntry.xaml.cs
  Content.Shared/Blueprint/BluebenchBoundUserInterfaceState.cs
  Content.Shared/Blueprint/BluebenchResearchPrototype.cs
  Content.Shared/Blueprint/BluebenchSystem.cs
  Resources/Locale/en-US/_tc14/bluebench.ftl
  Resources/Prototypes/_tc14/Entities/Objects/Materials/Sheets/other.yml
  Resources/Prototypes/_tc14/Entities/Structures/Machines/workbench.yml
Labels: Changes: UI

#80 seed entity table changes
  Resources/Prototypes/_tc14/Entities/Objects/Decoration/flora.yml
Labels: Changes: No C#

#79 screwdriver recipe change
  Resources/Prototypes/Recipes/Lathes/tools.yml
Labels: Changes: No C#

#78 Mortar
  Resources/Locale/en-US/tools/tool-qualities.ftl
  Resources/Prototypes/_tc14/Entities/Objects/Materials/wood.yml
  Resources/Prototypes/_tc14/Entities/Objects/Tools/stone.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/Graphs/Materials/brick.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/Graphs/tools.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/improvised.yml
  Resources/Prototypes/_tc14/Recipes/Crafting/tools.yml
  Resources/Prototypes/_tc14/tool_qualities.yml
  Resources/Textures/_tc14/Objects/Items/mortar.rsi/meta.json
  Resources/Textures/_tc14/Objects/Items/mortar.rsi/mortar.png
Labels: Changes: No C#, Changes: Sprites

#83 update fork ID in publish
  Tools/publish_multi_request.py
Labels: Changes: No C#

#84 Research Rebalance
  Resources/Prototypes/_tc14/Entities/Structures/Machines/workbench.yml
  Resources/Prototypes/_tc14/research_projects.yml
Labels: Changes: No C#

#85 craftable lighters
  Resources/Prototypes/_tc14/Recipes/Lathes/Packs/workbench.yml
  Resources/Prototypes/_tc14/Recipes/Lathes/tools.yml
Labels: Changes: No C#

#90 Modified the lobby backgrounds.
  Resources/Prototypes/_tc14/lobbyscreens.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/LobbyScreens/attributions.yml
  Resources/Textures/LobbyScreens/behonker.webp
  Resources/Textures/LobbyScreens/behonker.webp.yml
  Resources/Textures/LobbyScreens/campfire.webp
  Resources/Textures/LobbyScreens/campfire.webp.yml
  Resources/Textures/LobbyScreens/doomed.webp
  Resources/Textures/LobbyScreens/doomed.webp.yml
  Resources/Textures/LobbyScreens/janishootout.webp
  Resources/Textures/LobbyScreens/janishootout.webp.yml
  Resources/Textures/LobbyScreens/pharmacy.webp
  Resources/Textures/LobbyScreens/reclaimer-nuke.webp
  Resources/Textures/LobbyScreens/reclaimer-nuke.webp.yml
  Resources/Textures/LobbyScreens/skellyvstherev.webp
  Resources/Textures/LobbyScreens/skellyvstherev.webp.yml
  Resources/Textures/LobbyScreens/susstation.webp
  Resources/Textures/LobbyScreens/susstation.webp.yml
  Resources/Textures/LobbyScreens/terminalstation.webp
  Resources/Textures/LobbyScreens/terminalstation.webp.yml
  Resources/Textures/LobbyScreens/warden.webp
  Resources/Textures/LobbyScreens/warden.webp.yml
Labels: Changes: No C#

#91 Changed a couple publishing parameters ;)
  Tools/publish_multi_request.py
Labels: Changes: No C#

#94 Blueprint prototypes refactoring.
  Content.Shared/Blueprint/BluebenchSystem.cs
  Resources/Prototypes/_tc14/Entities/Structures/Machines/workbench.yml
  Resources/Prototypes/_tc14/ResearchProjects/engineering.yml
  Resources/Prototypes/_tc14/ResearchProjects/medical.yml
  Resources/Prototypes/_tc14/ResearchProjects/misc.yml
  Resources/Prototypes/_tc14/ResearchProjects/security.yml
  Resources/Prototypes/_tc14/research_projects.yml
Labels: Changes: No C#

#96 pda astro nav
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
Labels: Changes: No C#

#97 Torch improvements
  Content.Server/Light/EntitySystems/ExpendableLightSystem.cs
  Content.Shared/Light/Components/SharedExpendableLightComponent.cs
  Resources/Locale/en-US/light/components/expendable-light-component.ftl
  Resources/Prototypes/Entities/Objects/Misc/torch.yml
  Resources/Prototypes/Entities/Objects/Tools/flare.yml
  Resources/Prototypes/Entities/Objects/Tools/glowstick.yml
  Resources/Prototypes/Entities/Structures/Decoration/torches.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/lighting.yml
  Resources/Prototypes/Recipes/Construction/lighting.yml
  Resources/Textures/Structures/Decoration/torches.rsi/meta.json
  Resources/Textures/Structures/Decoration/torches.rsi/torch_lit.png
  Resources/Textures/Structures/Decoration/torches.rsi/torch_unlit.png
  Resources/Textures/Structures/Decoration/torches.rsi/wall_torch_lit.png
  Resources/Textures/Structures/Decoration/torches.rsi/wall_torch_unlit.png
Labels: Changes: Sprites

#99 TEMP: Workbench clothing recipes
  Resources/Prototypes/_tc14/Entities/Structures/Machines/workbench.yml
Labels: Changes: No C#, S: Needs Review
